### ISSUE TITLE
Root cres are broken

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#179]
The page https://www.opencre.org/root_cres does not show all the root topics, for example Input and output verification is not shown. For a full list, search on >>. About half is missing.

**Comment by northdpole** [comment]
problem is that the current implementation, treats the relationship "Related" as a bidirectional link.

Since the top level CREs missing have edges coming in to them, this means that they aren't root cres.

We can fix this by changing the filtering of graph nodes in the root_cre method. Coming up soon
